#ifndef SENSORDEMOENTITY_READER_H
#define SENSORDEMOENTITY_READER_H

/* Generated by flatcc 0.5.3-pre FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct SensorDemoEntity_table *SensorDemoEntity_table_t;
typedef const flatbuffers_uoffset_t *SensorDemoEntity_vec_t;
typedef flatbuffers_uoffset_t *SensorDemoEntity_mutable_vec_t;
#ifndef SensorDemoEntity_identifier
#define SensorDemoEntity_identifier flatbuffers_identifier
#endif
#define SensorDemoEntity_type_hash ((flatbuffers_thash_t)0xa85fb1fb)
#define SensorDemoEntity_type_identifier "\xfb\xb1\x5f\xa8"



struct SensorDemoEntity_table { uint8_t unused__; };

static inline size_t SensorDemoEntity_vec_len(SensorDemoEntity_vec_t vec)
__flatbuffers_vec_len(vec)
static inline SensorDemoEntity_table_t SensorDemoEntity_vec_at(SensorDemoEntity_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(SensorDemoEntity_table_t, vec, i, 0)
__flatbuffers_table_as_root(SensorDemoEntity)

__flatbuffers_define_scalar_field(0, SensorDemoEntity, id, flatbuffers_uint64, uint64_t, UINT64_C(0))
__flatbuffers_define_scalar_field(1, SensorDemoEntity, lightIntensity, flatbuffers_float, float, 0.000000f)
__flatbuffers_define_scalar_field(2, SensorDemoEntity, temperature, flatbuffers_float, float, 0.000000f)
__flatbuffers_define_scalar_field(3, SensorDemoEntity, humidity, flatbuffers_float, float, 0.000000f)
__flatbuffers_define_scalar_field(4, SensorDemoEntity, measuredAt, flatbuffers_uint64, uint64_t, UINT64_C(0))

#include "flatcc/flatcc_epilogue.h"
#endif /* SENSORDEMOENTITY_READER_H */
