#ifndef COMPRESSIONDEMOENTITY_READER_H
#define COMPRESSIONDEMOENTITY_READER_H

/* Generated by flatcc 0.5.3-pre FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct CompressionDemoEntity_table *CompressionDemoEntity_table_t;
typedef const flatbuffers_uoffset_t *CompressionDemoEntity_vec_t;
typedef flatbuffers_uoffset_t *CompressionDemoEntity_mutable_vec_t;
#ifndef CompressionDemoEntity_identifier
#define CompressionDemoEntity_identifier flatbuffers_identifier
#endif
#define CompressionDemoEntity_type_hash ((flatbuffers_thash_t)0xa2cec575)
#define CompressionDemoEntity_type_identifier "\x75\xc5\xce\xa2"



struct CompressionDemoEntity_table { uint8_t unused__; };

static inline size_t CompressionDemoEntity_vec_len(CompressionDemoEntity_vec_t vec)
__flatbuffers_vec_len(vec)
static inline CompressionDemoEntity_table_t CompressionDemoEntity_vec_at(CompressionDemoEntity_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(CompressionDemoEntity_table_t, vec, i, 0)
__flatbuffers_table_as_root(CompressionDemoEntity)

__flatbuffers_define_scalar_field(0, CompressionDemoEntity, id, flatbuffers_uint64, uint64_t, UINT64_C(0))
__flatbuffers_define_scalar_field(1, CompressionDemoEntity, timestamp, flatbuffers_uint64, uint64_t, UINT64_C(0))
__flatbuffers_define_vector_field(2, CompressionDemoEntity, userData, flatbuffers_int8_vec_t, 0)

#include "flatcc/flatcc_epilogue.h"
#endif /* COMPRESSIONDEMOENTITY_READER_H */
